spring.jmx:
  enabled: false
spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:bootexample;MODE=MySQL
server:
  port: 8090
  
#todo: make sure to always enable security in production
security:
  basic:
    enabled: false
#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.
#default project info followed by actual injected pom-specified values.
project:
  name: person-service
  version: 0.1
  description: person-service
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

spring.jpa:
  hibernate.ddl-auto: create-drop
---
spring:
  profiles: mysql
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rsmortgage
    username: root
    password: 12345678
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: update # todo: in non-dev environments, comment this out:

